### ISSUE TITLE
Need a way to substitute Models with other types

### ISSUE THREAD

**Issue by who** [kongchen/swagger-maven-plugin#162]
We should create a way for users of swagger-maven-plugin to substitute classes for other types.

For instance, in the example below, I would like to substitute `PetName` with `string`.

Springfox has a really elegant way of doing this, and can be seen here: 
http://springfox.github.io/springfox/javadoc/snapshot/springfox/documentation/spring/web/plugins/Docket.html#directModelSubstitute(java.lang.Class,%20java.lang.Class)

**Class**

```
public class PetName {
    private final String name;
    
    @JsonCreator
    public static PetName fromString(@JsonProperty("name") String name){
        if(!ValidationUtil.isValidIdentifier(name)){
            throw new IllegalArgumentException("Invalid pet name");
        }        
        return new PetName(name);
    }

    public PetName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return name;
    }
}
```

**Current spec output**

```
  "definitions" : {
    "Pet" : {
      "properties" : {
        ...
        "petName" : {
          "$ref" : "#/definitions/PetName"
        }
        ...
      }
    }
```

**Desired spec output**

```
  "definitions" : {
    "Pet" : {
      "properties" : {
        ...
        "petName" : {
          "type" : "string"
        }
        ...
      }
    }
```

**Comment by kongchen** [comment]
I add a configuration item `<modelSubstitute>` in `<apiSource>`, it points to a file called *Model Substitute File*.
Model substitute file is a simple text file with multiple lines, each line tells the plugin to substitutes a model class with the supplied substitute, and the 2 classes should be seperated by a `:`. 

e.g The line:

```
com.foo.bar.PetName : java.lang.String
```

would tell the plugin substitute `com.foo.bar.PetName` with `java.lang.String`, 
and the generated `swagger.json` will become:

```
 "definitions" : {
    "Pet" : {
      "properties" : {
        ...
        "petName" : {
          "type" : "string"
        }
        ...
      }
    }
```
instead of :

```
 "definitions" : {
    "Pet" : {
      "properties" : {
        ...
        "petName" : {
          "$ref" : "#/definitions/PetName"
        }
        ...
      }
    }
```

See https://github.com/kongchen/swagger-maven-plugin/blob/master/src/test/resources/plugin-config.xml#L55 for the pom configration.

See https://github.com/kongchen/swagger-maven-plugin/blob/master/src/test/resources/override.map for the Model Substitute File.

**Comment by who** [comment]
Very nice!  I will test this in my current implementations.

**Comment by kongchen** [comment]
Great, thanks for the good suggestion.

**Comment by who** [comment]
I just validated that this is working, so I'll close this.  Thanks again.

**Comment by spyro2000** [comment]
I just get a nullpointer exception, no matter where I put the substitution file.

Tried:

- Project Root with leading "/" in the path and without
- Resources Directory

`<apiSource>
   <modelSubstitute>/swaggerModelSubstitutions.csv</modelSubstitute>
 </apiSource>`

File content:

`java.time.OffsetDateTime : java.lang.String`

Nothing works:

 Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.8:generate (default-cli) on project ijix-cfdmd-demands: null: MojoExecutionException: NullPointerException

**Comment by ghost** [comment]
@spyro2000 A long long time ago... The NullPointer happens when the file for modelSubstitute is not found ensure the file is available.
