### ISSUE TITLE
3.1.0 version not scanning the classpath properly?

### ISSUE THREAD

**Issue by typekpb** [kongchen/swagger-maven-plugin#189]
I tried to update from 3.0-M1 to 3.1.0 but no classes are shown in the generated `swagger.json` file.

Not sure why, but trying the official example failed for me as well, see: https://github.com/typekpb/swagger-maven-example

once running `mvn compile` swagger.json is generated with following structure:

		{
		  "swagger" : "2.0",
		  "info" : {
			"description" : "This is a sample for swagger-maven-plugin",
			"version" : "v1",
			"title" : "Swagger Maven Plugin Sample",
			"termsOfService" : "http://www.github.com/kongchen/swagger-maven-plugin",
			"contact" : {
			  "name" : "Kong Chen",
			  "url" : "http://kongch.com",
			  "email" : "kongchen@gmail.com"
			},
			"license" : {
			  "name" : "Apache 2.0",
			  "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
			}
		  },
		  "host" : "petstore.swagger.wordnik.com",
		  "basePath" : "/api",
		  "schemes" : [ "http", "https" ]
		}

am I missing here some important setting?

**Comment by who** [comment]
@typekpb 3.1.0 uses the new version of swagger-core.  In the latest swagger-core version, they changed the package names from com.wordnik.* to io.swagger.*.  

Because of this, you will have to:

1. Use 1.5 of io.swagger.swagger-core in your pom
2. Change all of your swagger annotations from their com.wordnik.* namespace to to io.swagger.* namespaces.

**Comment by typekpb** [comment]
works for me now, thanks!
