### ISSUE TITLE
Add option to deploy the generated swager.json

### ISSUE THREAD

**Issue by dantran** [kongchen/swagger-maven-plugin#254]
This way, a build can aggregate a snumber of swagger api files via maven dependencies

**Comment by who** [comment]
@dantran 

Could you please elaborate on this request?  What use cases are you trying to solve for?

**Comment by dantran** [comment]
My product has a number of components. Each component generates swagger.json, then deploy that file to maven repo a classifier using build-helper-maven-plugin.  Then we have another module to aggregate those swagger.json files into another artifact.  

It is a common practice to the plugin have the ablity to deploy its generated/build artifacts

**Comment by raptortech-js** [comment]
Why would users of the maven repo want swagger.json files?

**Comment by dantran** [comment]
@raptortech-js we have other teams consuming our swagger.json to generate java client using swagger-codegen

I would propose to introduce swaggerClassifer to apiSource.  If present, swagger-m-p will generate 'swaggerClassfier'.json and also deploy to maven repo.  Can I propose a PR?

**Comment by mortias** [comment]
Can't you use the standard maven plugins like 'assembly' does? Create a zip and upload it in nexus? Make the zip filename unique per module and keep the json filename coherent?

**Comment by dantran** [comment]
@mortias, I am using build-helper to attach the genenerated swagger.json to Maven for deplomnet purpose, but having swagger to handle its own output files gives better user experience

**Comment by who** [comment]
@dantran 

Thanks for the clarification. You're the first person to ask for this (that I know of). I don't think that swagger spec deployment falls inside the goal of this plugin.

The problem with having swagger-maven-plugin handle the output file in the manner you are suggesting is that not everyone is going to be doing it this way. For example, some people might want to create a tar file and upload to nexus, some people might want to create a zip file and upload to github, some people might want to upload it as a gist, etc. This is not the concern of swagger-maven-plugin.

I recommend that you implement another deployment/archival plugin be used after swagger-maven-plugin executes in order to handle the swagger.json files according to your wishes. The goal of swagger-maven-plugin is to generate a spec and put it on the local disk. Any further action on that file is up to the discretion of the developer, and should be handled by a downstream maven plugin or other instruction.

**Comment by mortias** [comment]
True, we also do ex. "Post processing" on the json files and create a catalog but thats not related to the plugin.. making the filename variable could be an output feature however most probably you would like to give it the name of your maven build artifact which needs feed from maven via a java template?

**Comment by dantran** [comment]
@who 
Yes, I did implement the post swagger-maven-plugin to using build-helper-maven-plugin.  I thought it would be nice from swagger-m-p perspective to implement this feature and there much less configuration for user like me  ( one line at swagger, rather then 15 line in build-helper)

**Comment by dantran** [comment]
related to #178, i can provide this enhance as well

**Comment by dantran** [comment]
@who could you deploy a snapshot to oss.sonatype.com? Thanks for the merge.  When is next release?

**Comment by who** [comment]
@dantran 3.1.2 has been released. http://mvnrepository.com/artifact/com.github.kongchen/swagger-maven-plugin/3.1.2
